### ISSUE TITLE
Uncaught ReferenceError: Wii is not defined 

### ISSUE THREAD

**Issue by nielvrom** [ryanmcgrath/wii-js#1]
I always get the error "Uncaught ReferenceError: Wii is not defined".
What could cause the problem?

Thanks in advance!

**Comment by ryanmcgrath** [comment]
Can you show some example code? Others have run into this issue but it was usually with their setup. Happy to help debug.

**Comment by nielvrom** [comment]
Is it normal that the script doesn't work in a browser on a desktop? (for example: Google Chrome)

**Comment by ryanmcgrath** [comment]
Hey,

Ah, the goal was never really to run it on a browser, but there's nothing
that should prevent it from running on the browser. It's probably a check
or two failing somewhere regarding polling the other 3 wii remotes - the
primary one just fires based off standard DOM events...

If I get some time later tonight I could try and take a look, otherwise
you're welcome to fork and patch it. :)
- Ryan

On Wed, Feb 27, 2013 at 9:39 AM, nielvrom notifications@github.com wrote:

> Is it normal that the script doesn't work in a browser on a desktop? (for
> example: Google Chrome)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ryanmcgrath/wii-js/issues/1#issuecomment-14176718
> .

## 

Skype: ryanmcgrathr
Twitter: http://twitter.com/ryanmcgrath/
Web: http://venodesigns.net/
GitHub: http://github.com/ryanmcgrath/

**Comment by nielvrom** [comment]
I am testing with only one wii remote. Could that be the problem?

**Comment by ryanmcgrath** [comment]
In the Wii browser, or on the desktop?

On Wed, Feb 27, 2013 at 9:44 AM, nielvrom notifications@github.com wrote:

> I am testing with only one wii remote. Could that be the problem?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ryanmcgrath/wii-js/issues/1#issuecomment-14177011
> .

## 

Skype: ryanmcgrathr
Twitter: http://twitter.com/ryanmcgrath/
Web: http://venodesigns.net/
GitHub: http://github.com/ryanmcgrath/

**Comment by nielvrom** [comment]
on the desktop

**Comment by ryanmcgrath** [comment]
Hey,

Well, the Wii remotes can't communicate with an arbitrary browser on the
desktop. The only way the library works to interact with Wii remotes is in
the browser on the Wii itself - it's a specific build of Opera that's
tailored to the console.
- Ryan

On Wed, Feb 27, 2013 at 11:48 AM, nielvrom notifications@github.com wrote:

> on the desktop
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ryanmcgrath/wii-js/issues/1#issuecomment-14184490
> .

## 

Skype: ryanmcgrathr
Twitter: http://twitter.com/ryanmcgrath/
Web: http://venodesigns.net/
GitHub: http://github.com/ryanmcgrath/
